[build]
  publish = "public"

[functions]
  included_files = ["public/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/finance"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/aptitude"
  to = "/aptitude.html"
  status = 200
